name: theme_generator_x
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  recase: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
