name: theme_generator_x
description: Theme extension generator
version: 0.0.6
repository: https://github.com/jWinterDay/theme_generator_x

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  path: ^1.8.3
  recase: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.2
  melos: ^3.1.1
  # flutter_test:
  #   sdk: flutter
  # test: ^1.24.1
  # analyzer: ^5.13.0

executables:
  theme_generator_x: theme_generator_x_cli
